pygments: true
permalink: /articles/:title
destination: __local

env:
  prod:
    img: http://images.thomasjbradley.ca
    img2: http://images2.thomasjbradley.ca
    static: http://static.thomasjbradley.ca
  dev:
    img: /img
    img2: /img2
    static: /static

stylus:
  path: ./static
  compress: true
  use: :nib

sitemap:
  url: http://thomasjbradley.com
  hasposts:
    - index.html
    - articles.html
  exclude:
    - htaccess
    - theme.styl
    - demo.styl
    - articles.xml

exclude:
  - deploy.sh
  - update-github-assets.sh
  - exclude-root.txt
  - exclude-base.txt
  - pingomatic.xml
  - footer.styl
  - general.styl
  - grid.styl
  - header.styl
  - misc.styl
  - code.styl
  - tables.styl
  - normalize.styl
  - config.styl
  - site-title.styl
  - blog-posts.styl
